const products = [
  {id:'kit',name:'Ayurvedic Hair Mask Kit',detail:'Amla, Reetha, Hibiscus, Shikakai & Bhringraj • 750g',price:399,category:'combo hair',tag:'Best value',image:'https://m.media-amazon.com/images/I/71G6cxz0mJL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'orange',name:'Orange Peel Powder',detail:'100% pure orange peel powder • 150g',price:164,category:'skin',image:'https://m.media-amazon.com/images/I/711mtVb-XiL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'neem',name:'Neem Powder',detail:'For hair, face & skin • 150g',price:120,category:'hair skin',image:'https://m.media-amazon.com/images/I/611ff3OPZmL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'amla',name:'Amla Powder',detail:'100% pure Indian gooseberry powder • 150g',price:169,category:'hair',image:'https://m.media-amazon.com/images/I/611maU14CeL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'hibiscus',name:'Hibiscus Powder',detail:'100% pure hibiscus powder • 150g',price:179,category:'hair skin',image:'https://m.media-amazon.com/images/I/71oBdX0DjcL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'shikakai',name:'Shikakai Powder',detail:'100% pure shikakai powder • 150g',price:199,category:'hair',image:'https://m.media-amazon.com/images/I/71xIodaNnOL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'reetha',name:'Reetha Powder',detail:'For a traditional hair-care ritual • 150g',price:199,category:'hair',image:'https://m.media-amazon.com/images/I/71-h+ns9NeL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'moringa',name:'Moringa Leaf Powder',detail:'Moringa leaf powder • 150g',price:199,category:'skin',image:'https://m.media-amazon.com/images/I/61OqwKcp5cL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'multani',name:'Multani Mitti',detail:'100% natural Multani Mitti • 150g',price:139,category:'skin',image:'https://m.media-amazon.com/images/I/71o5HgnR75L._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'bhringraj',name:'Bhringraj Powder',detail:'For a traditional hair-care ritual • 150g',price:179,category:'hair',image:'https://m.media-amazon.com/images/I/71+07zufsaL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'face-combo',name:'Orange Peel + Multani Mitti',detail:'Face pack & skin care combo • 75g each',price:199,category:'combo skin',tag:'Combo pack',image:'https://m.media-amazon.com/images/I/71cLjlWk5DL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'}
];
let cart = JSON.parse(localStorage.getItem('vellon-cart') || '[]');
const money = value => `₹${value.toLocaleString('en-IN')}`;
const grid = document.querySelector('#product-grid');
function renderProducts(filter='all') { grid.innerHTML = products.filter(p=>filter==='all'||p.category.includes(filter)).map(p=>`<article class="product-card">${p.tag?`<span class="tag">${p.tag}</span>`:''}<div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy" /></div><div class="product-info"><p><b>${p.name}</b><br><small>${p.detail}</small></p><div class="price-row"><strong class="price">${money(p.price)}</strong><button class="add" aria-label="Add ${p.name} to bag" data-add="${p.id}">+</button></div></div></article>`).join(''); }
function updateCart(){localStorage.setItem('vellon-cart',JSON.stringify(cart));document.querySelector('#cart-count').textContent=cart.reduce((sum,i)=>sum+i.qty,0);document.querySelector('#cart-total').textContent=money(cart.reduce((sum,i)=>sum+i.qty*i.price,0));const list=document.querySelector('#cart-items');list.innerHTML=cart.length?cart.map(i=>`<div class="cart-line"><img src="${i.image}" alt="" /><p><b>${i.name}</b><small>${i.qty} × ${money(i.price)}</small></p><button data-remove="${i.id}">Remove</button></div>`).join(''):'<p class="empty">Your bag is waiting for something natural.</p>';document.querySelector('#checkout').disabled=!cart.length}
function add(id){const product=products.find(p=>p.id===id);const item=cart.find(p=>p.id===id);item?item.qty++:cart.push({...product,qty:1});updateCart();openCart()}
function openCart(){document.querySelector('#cart-drawer').classList.add('open');document.querySelector('#scrim').classList.add('open');document.querySelector('#cart-drawer').setAttribute('aria-hidden','false')}
function closeCart(){document.querySelector('#cart-drawer').classList.remove('open');document.querySelector('#scrim').classList.remove('open');document.querySelector('#cart-drawer').setAttribute('aria-hidden','true')}
grid.addEventListener('click',e=>{const id=e.target.dataset.add;if(id)add(id)});document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');button.classList.add('active');renderProducts(button.dataset.filter)}));document.querySelector('#cart-button').onclick=openCart;document.querySelector('#close-cart').onclick=closeCart;document.querySelector('#scrim').onclick=closeCart;document.querySelector('#cart-items').onclick=e=>{const id=e.target.dataset.remove;if(id){cart=cart.filter(p=>p.id!==id);updateCart()}};
document.querySelector('#shipping-form').onsubmit=async event=>{event.preventDefault();const button=document.querySelector('#checkout');const shipping=Object.fromEntries(new FormData(event.currentTarget));button.disabled=true;button.textContent='Preparing your order…';try{const items=cart.map(({id,name,qty,price})=>({id,name,qty,price}));const response=await fetch('/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,shipping})});const order=await response.json();if(!response.ok)throw new Error(order.error||'Unable to start payment');const razorpay=new Razorpay({key:order.key,amount:order.amount,currency:'INR',name:'Vellon Organic',description:`${cart.reduce((n,i)=>n+i.qty,0)} item(s)`,order_id:order.id,prefill:{name:shipping.name,contact:shipping.phone},notes:{shipping_address:`${shipping.address}, ${shipping.city}, ${shipping.state} - ${shipping.pincode}`},theme:{color:'#1c4a31'},handler:async payment=>{try{const verified=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payment,items,shipping})});const confirmation=await verified.json();if(!verified.ok)throw new Error(confirmation.error);cart=[];updateCart();closeCart();event.currentTarget.reset();alert(`Thank you! Your order ${confirmation.orderId} is received. We will confirm it shortly.`)}catch(error){alert(error.message+' Please keep your payment ID and contact us at vellonindustries@gmail.com.')}}});razorpay.open()}catch(error){alert(error.message+' Please contact us at vellonindustries@gmail.com.')}finally{button.disabled=!cart.length;button.innerHTML='Buy now <span>→</span>'}};
renderProducts();updateCart();document.querySelector('#year').textContent=new Date().getFullYear();
