const products=[
  {id:'kit',name:'Ayurvedic Hair Mask Kit',detail:'Amla, Reetha, Hibiscus, Shikakai & Bhringraj • 750g',price:399,category:'combo hair',tag:'Best value',image:'https://m.media-amazon.com/images/I/71G6cxz0mJL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'orange',name:'Orange Peel Powder',detail:'100% pure orange peel powder • 150g',price:164,category:'skin',image:'https://m.media-amazon.com/images/I/711mtVb-XiL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'neem',name:'Neem Powder',detail:'For hair, face & skin • 150g',price:120,category:'hair skin',image:'https://m.media-amazon.com/images/I/611ff3OPZmL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'amla',name:'Amla Powder',detail:'100% pure Indian gooseberry powder • 150g',price:169,category:'hair',image:'https://m.media-amazon.com/images/I/611maU14CeL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'hibiscus',name:'Hibiscus Powder',detail:'100% pure hibiscus powder • 150g',price:179,category:'hair skin',image:'https://m.media-amazon.com/images/I/71oBdX0DjcL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'shikakai',name:'Shikakai Powder',detail:'100% pure shikakai powder • 150g',price:199,category:'hair',image:'https://m.media-amazon.com/images/I/71xIodaNnOL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'reetha',name:'Reetha Powder',detail:'For a traditional hair-care ritual • 150g',price:199,category:'hair',image:'https://m.media-amazon.com/images/I/71-h+ns9NeL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'moringa',name:'Moringa Leaf Powder',detail:'Moringa leaf powder • 150g',price:199,category:'skin',image:'https://m.media-amazon.com/images/I/61OqwKcp5cL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'multani',name:'Multani Mitti',detail:'100% natural Multani Mitti • 150g',price:139,category:'skin',image:'https://m.media-amazon.com/images/I/71o5HgnR75L._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'bhringraj',name:'Bhringraj Powder',detail:'For a traditional hair-care ritual • 150g',price:179,category:'hair',image:'https://m.media-amazon.com/images/I/71+07zufsaL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'},
  {id:'face-combo',name:'Orange Peel + Multani Mitti',detail:'Face pack & skin care combo • 75g each',price:199,category:'combo skin',tag:'Combo pack',image:'https://m.media-amazon.com/images/I/71cLjlWk5DL._AC_CR0%2C0%2C0%2C0_SX704_SY660_.jpg'}
];
let cart=JSON.parse(localStorage.getItem('vellon-cart')||'[]');const money=v=>`₹${v.toLocaleString('en-IN')}`;const grid=document.querySelector('#product-grid');
function renderProducts(filter='all'){grid.innerHTML=products.filter(p=>filter==='all'||p.category.includes(filter)).map(p=>`<article class="product-card" data-product="${p.id}">${p.tag?`<span class="tag">${p.tag}</span>`:''}<button class="product-view" aria-label="View ${p.name}"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-info"><p><b>${p.name}</b><br><small>${p.detail}</small></p><div class="price-row"><strong class="price">${money(p.price)}</strong><span class="view-label">View</span></div></div></button></article>`).join('')}
function updateCart(){localStorage.setItem('vellon-cart',JSON.stringify(cart));document.querySelector('#cart-count').textContent=cart.reduce((s,i)=>s+i.qty,0);document.querySelector('#cart-total').textContent=money(cart.reduce((s,i)=>s+i.qty*i.price,0));const list=document.querySelector('#cart-items');list.innerHTML=cart.length?cart.map(i=>`<div class="cart-line"><img src="${i.image}" alt=""><p><b>${i.name}</b><small>${i.qty} × ${money(i.price)}</small></p><button data-remove="${i.id}">Remove</button></div>`).join(''):'<p class="empty">Your bag is waiting for something natural.</p>';document.querySelector('#checkout').disabled=!cart.length}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({...p,qty:1});updateCart();closeProduct();openCart()}
function openCart(){document.querySelector('#cart-drawer').classList.add('open');document.querySelector('#scrim').classList.add('open');document.querySelector('#cart-drawer').setAttribute('aria-hidden','false')}
function closeCart(){document.querySelector('#cart-drawer').classList.remove('open');document.querySelector('#scrim').classList.remove('open');document.querySelector('#cart-drawer').setAttribute('aria-hidden','true')}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;document.querySelector('#product-dialog-title').textContent=p.name;document.querySelector('#detail-image').src=p.image;document.querySelector('#detail-image').alt=p.name;document.querySelector('#detail-copy').textContent=p.detail;document.querySelector('#detail-price').textContent=money(p.price);document.querySelector('#detail-add').dataset.add=p.id;document.querySelector('#detail-thumbs').innerHTML=`<button class="thumb selected" data-image="${p.image}" aria-label="Product image"><img src="${p.image}" alt=""></button>`;document.querySelector('#product-dialog').showModal()}
function closeProduct(){document.querySelector('#product-dialog').close()}
grid.onclick=e=>{const card=e.target.closest('[data-product]');if(card)openProduct(card.dataset.product)};document.querySelector('#product-dialog').onclick=e=>{if(e.target===e.currentTarget)closeProduct();const image=e.target.closest('[data-image]')?.dataset.image;if(image){document.querySelector('#detail-image').src=image}const id=e.target.closest('[data-add]')?.dataset.add;if(id)add(id)};document.querySelector('#close-product').onclick=closeProduct;
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');renderProducts(b.dataset.filter)});document.querySelector('#cart-button').onclick=openCart;document.querySelector('#close-cart').onclick=closeCart;document.querySelector('#scrim').onclick=closeCart;document.querySelector('#cart-items').onclick=e=>{const id=e.target.dataset.remove;if(id){cart=cart.filter(p=>p.id!==id);updateCart()}};
document.querySelector('#shipping-form').onsubmit=async event=>{event.preventDefault();const button=document.querySelector('#checkout');const shipping=Object.fromEntries(new FormData(event.currentTarget));button.disabled=true;button.textContent='Preparing your order…';try{const items=cart.map(({id,name,qty,price})=>({id,name,qty,price}));const response=await fetch('/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,shipping})});const order=await response.json();if(!response.ok)throw new Error(order.error||'Unable to start payment');const razorpay=new Razorpay({key:order.key,amount:order.amount,currency:'INR',name:'Vellon Organic',description:`${cart.reduce((n,i)=>n+i.qty,0)} item(s)`,order_id:order.id,prefill:{name:shipping.name,contact:shipping.phone},theme:{color:'#1c4a31'},handler:async payment=>{try{const verified=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payment,items,shipping})});const confirmation=await verified.json();if(!verified.ok)throw new Error(confirmation.error);cart=[];updateCart();closeCart();event.currentTarget.reset();alert(`Thank you! Your order ${confirmation.orderId} is received. We will confirm it shortly.`)}catch(error){alert(error.message+' Please keep your payment ID and contact us at vellonindustries@gmail.com.')}}});razorpay.open()}catch(error){alert(error.message+' Please contact us at vellonindustries@gmail.com.')}finally{button.disabled=!cart.length;button.innerHTML='Buy now <span>→</span>'}};
async function refreshPrices(){try{const response=await fetch('/api/catalogue');if(!response.ok)return;const {catalogue}=await response.json();products.forEach(p=>{if(catalogue[p.id])p.price=catalogue[p.id].price});cart.forEach(i=>{if(catalogue[i.id])i.price=catalogue[i.id].price});renderProducts();updateCart()}catch{}}
renderProducts();updateCart();refreshPrices();document.querySelector('#year').textContent=new Date().getFullYear();
